### ISSUE TITLE
switch to Qt5

### ISSUE THREAD

**Issue by bigeagle** [bigeagle/danmaQ#11]
so that more modern platforms can be supported.

**Comment by xavieryao** [comment]
>  more modern platforms   

大鹰宣称 OS X 比起 Arch 是一个更先进的平台

**Comment by bigeagle** [comment]
不要听得风就是雨！

**Comment by binli** [comment]
现在基本都qt5的库了，赶快支持一下啊

**Comment by xavieryao** [comment]
@bigeagle 忙着实习…

On Thu, Sep 15, 2016 at 1:09 PM +0800, "Bin Li" <notifications@github.com<mailto:notifications@github.com>> wrote:

现在基本都qt5的库了，赶快支持一下啊

―

**Comment by binli** [comment]
今天想用一下，结果编译不了，我试试 AppImage 先
