### ISSUE TITLE
这个怎么实现微信的功能啊

### ISSUE THREAD

**Issue by ghost** [bigeagle/danmaQ#17]
就是如果每个人发送给微信公众号，然后能够将这些显示在弹幕上，谢谢

**Comment by sztsian** [comment]
微信不是开源软件。据我所知，微信没有公开的API，所以这个应该没有办法。如果想使用弹幕功能，建议使用开源的聊天方式，或者至少是开放API的方式。

**Comment by ghost** [comment]
我在https://www.zhihu.com/question/27045473 上边看到写着可以支持微信公众号，可是具体怎么操作却不知道，微信有第三方的api，叫itchat，我之前用过。

**Comment by bigeagle** [comment]
写一个 API gateway 就可以了，danmaQ 只是客户端

**Comment by ghost** [comment]
好的好的，谢谢
