### ISSUE TITLE
Please fulfill GPL licence requirements

### ISSUE THREAD

**Issue by sztsian** [bigeagle/danmaQ#18]
The package failed rpmlint due to following files do not have licence info while your project licence is GPLv3. Please fix it.

Unknown or generated
--------------------
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/.travis.yml
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/CMakeLists.txt
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/LICENSE
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/README.md
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/screenshots/window.png
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/screenshots/xiaowang.png
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/.ycm_extra_conf.py
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/CMakeLists.txt
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/danmaQ_app.cpp
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/danmaQ_app.h
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/danmaku.h
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/danmaku_ui.cpp
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/danmaku_ui.h
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/danmaku_window.cpp
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/danmaku_window.h
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/icons.qrc
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/icons/statusicon.ico
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/icons/statusicon.png
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/icons/statusicon.svg
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/icons/statusicon_disabled.png
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/main.cpp
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/subscriber.cpp
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/src/subscriber.h
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/tests/CMakeLists.txt
danmaQ-ab838667d53c71c6cf8ac94dd109fcd009460530/tests/json_test.cpp

**Comment by bigeagle** [comment]
Any examples?

**Comment by sztsian** [comment]
The best case is, if you can add licence statement in the beginning of each file, like https://github.com/RHQE/kdump-test/blob/master/lib/kdump.sh
If it is too much work, can you clearly state the licence of each code files in this issue, so that I can use this issue as the justification reference.

**Comment by sztsian** [comment]
Hi,
If you are just too busy, I am fine to postpone this, as this is already in Fedora as danmaq.
Besides, only source files (in this case .cpp, .h, .py) is suggested to add license.
