### ISSUE TITLE
seems that latest windows build lacks several Qt plugin files

### ISSUE THREAD

**Issue by jodoe-9331** [bigeagle/danmaQ#23]
如题，https://github.com/tuna/danmaQ/releases/tag/qt5-msvc
启动时会提示：
This application failed to start because it could not find or load the Qt platform plugin "windows" in "".
我最近用的旧电脑，上面没有 Qt 的开发环境，只能根据搜索的结果猜测是缺了 Qt 相关文件。

**Comment by Harry-Chen** [comment]
好的，我最近也注意到了这个问题，会修复的。

**Comment by jodoe-9331** [comment]
试了一下 0.2.1，在程序根目录加上缺的 platforms\qwindowsd.dll 就能正常运行了

**Comment by Harry-Chen** [comment]
是的，我也已经找到问题了，感谢告知。
下一个版本发布时会修复，多谢。
