### ISSUE TITLE
missing danmaQ.desktop file

### ISSUE THREAD

**Issue by hosiet** [bigeagle/danmaQ#25]
`danmaQ.desktop` is missing now in repository.

**Comment by hosiet** [comment]
Proposed `danmaQ.desktop`:

```
[Desktop Entry]
Name=danmaQ
Name[zh_CN]=danmaQ 弹幕客户端
Comment=Show danmaku on screen
Comment[zh_CN]=在桌面上显示弹幕
GenericName=danmaQ
Exec=danmaQ
Icon=danmaQ
Terminal=false
Type=Application
Categories=Qt;Utility;
Keywords=danmaQ;
Keywords[zh_CN]=弹幕;
```

**Comment by hosiet** [comment]
`.desktop` file needs icons. Proposed installation of icons:

```
src/icons/statusicon.png => usr/share/icons/hicolor/64x64/apps/danmaQ.png
src/icons/statusicon.svg => usr/share/icons/hicolor/scalable/apps/danmaQ.svg
```

Renaming files (rename statsicon.* to danmaQ.*) would be much more preferable.

**Comment by bigeagle** [comment]
pushed via dec2f83b408859933023b354031cd964682bd0eb

**Comment by sztsian** [comment]
Well, I just know this can be an issue as well.
Prior that this, I made a hack in [SPEC file](https://src.fedoraproject.org/rpms/danmaq/blob/master/f/danmaq.spec) to add desktop file.

**Comment by hosiet** [comment]
Fixed in latest commit.
