### ISSUE TITLE
l10n support needed

### ISSUE THREAD

**Issue by Harry-Chen** [bigeagle/danmaQ#28]
Plan to add translation for: 
* [x] zh_CN
* [x] zh_TW
* [x] ja_JP

Then: 
* [x] Rename translation files and the looking-up mechanism

**Comment by sztsian** [comment]
@LionNatsu Can you help for ja_JP?

**Comment by Harry-Chen** [comment]
Just copy `src\translations\il8n_zh.ts` to `il8_ja.ts` and modify its contents will do.
Compiling is now broken, I will fix it soon.

**Comment by LionNatsu** [comment]
@sztsian Will do.
