### ISSUE TITLE
Incorrect tag version

### ISSUE THREAD

**Issue by hosiet** [bigeagle/danmaQ#34]
Tag "0.12" earlier than "0.2.2" however 0.12 > 0.2.2.

**Comment by sztsian** [comment]
Personally I just ignore 0.12. Or totally see it as 0.1.2. But yes, in release-monitoring.org it also shows 0.12 is newer
https://release-monitoring.org/project/16133/
I suggest TUNA to remove the 0.12 release.

**Comment by Harry-Chen** [comment]
I have renamed tag v0.12 to v0.1.2 to fix this issue. Thanks.
