### ISSUE TITLE
v0.2.3 Failed to build on Fedora

### ISSUE THREAD

**Issue by sztsian** [bigeagle/danmaQ#50]
When compiling following the readme, following error happened.

> [zsun@x240 danmaQ-0.2.3]$ mkdir build
> [zsun@x240 danmaQ-0.2.3]$ cd build/
> [zsun@x240 build]$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release 
> -- The C compiler identification is GNU 7.1.1
> -- The CXX compiler identification is GNU 7.1.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
> -- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
> -- Looking for gethostbyname
> -- Looking for gethostbyname - found
> -- Looking for connect
> -- Looking for connect - found
> -- Looking for remove
> -- Looking for remove - found
> -- Looking for shmat
> -- Looking for shmat - found
> -- Found X11: /usr/lib64/libX11.so
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/danmaQ-0.2.3/build
> [zsun@x240 build]$ make
> Scanning dependencies of target translations
> [  5%] Generating ../../../src/translations/zh_CN.qm
> /bin/sh: LRELEASE-NOTFOUND: command not found
> make[2]: *** [src/translations/CMakeFiles/translations.dir/build.make:63: ../src/translations/zh_CN.qm] Error 127
> make[1]: *** [CMakeFiles/Makefile2:216: src/translations/CMakeFiles/translations.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

Versions on my laptop:

qt5-qtxmlpatterns-5.7.1-5.fc26.x86_64
qt5-qtx11extras-5.7.1-3.fc26.x86_64
qt5-qtbase-gui-5.7.1-19.fc26.x86_64
qt-4.8.7-28.fc26.x86_64
qt5-qtsvg-5.7.1-3.fc26.x86_64
qt5-qtwayland-5.7.1-4.fc26.x86_64
qt-settings-26-1.fc26.noarch
qt5-qttools-libs-designer-5.7.1-5.fc26.x86_64
qt5-qtx11extras-devel-5.7.1-3.fc26.x86_64
qt5-qtdeclarative-5.7.1-8.fc26.x86_64
qt5-srpm-macros-5.8.0-2.fc26.noarch
qt5-qtbase-5.7.1-19.fc26.x86_64
qt5-qttools-5.7.1-5.fc26.x86_64
qt5-qttools-common-5.7.1-5.fc26.noarch
qt3-3.3.8b-69.fc26.x86_64
qt5-qtbase-devel-5.7.1-19.fc26.x86_64
qt5-qtdeclarative-devel-5.7.1-8.fc26.x86_64
qt-common-4.8.7-28.fc26.noarch
qt5-rpm-macros-5.8.0-2.fc26.noarch
qt-x11-4.8.7-28.fc26.x86_64
qt5-qtbase-common-5.7.1-19.fc26.noarch
cmake-3.9.0-8.fc26.x86_64

**Comment by jiegec** [comment]
You might need some package named like `lrelease-qt5` or `qt5-linguist` installed for the `lrelease` tool.
I am looking for the exact package name for it.
The package name in openSUSE seems to be `libqt5-linguist`.

**Comment by sztsian** [comment]
Thanks for the help. I'll solve it soon in Fedora

**Comment by Harry-Chen** [comment]
Fixed by ad4c45ca085bc84651abb170238027038639e46d

**Comment by sztsian** [comment]
> Fixed by ad4c45c

Along with https://github.com/tuna/danmaQ/commit/f2222024df933e6bdacb5de6952863259738b0e1
