### ISSUE TITLE
win7 32位系统上运行有问题

### ISSUE THREAD

**Issue by MrSong0607** [bigeagle/danmaQ#57]
![_20180205091015](https://user-images.githubusercontent.com/13636643/35784622-af20f132-0a54-11e8-8f45-0596cbc9405b.png)

如图

**Comment by jiegec** [comment]
您使用的 danmaQ 二进制仅运行于 x86_64 架构（即Intel 64-bit），故不能在您使用的 32位系统上运行。

**Comment by Harry-Chen** [comment]
正如文件名所描述的 ，这个版本是为64位 Windows 发布的。目前由于我手头没有32位的 Qt 环境，所以暂不能提供 32 位版本的 danmaQ。

**Comment by MrSong0607** [comment]
知道了，谢谢
