### ISSUE TITLE
Where is danmaq-git...

### ISSUE THREAD

**Issue by acgtyrant** [bigeagle/danmaQ#8]
No search result in AUR.

**Comment by acgtyrant** [comment]
What is the license? I am packaging danmaQ.

**Comment by bigeagle** [comment]
GPLv3

## 

Justin Wong

On Fri, Dec 25, 2015, at 21:20, Isaac Ge wrote:

> What is the license? I am packaging danmaQ.
> 
> —
> Reply to this email directly or view it on GitHub[1]. 

Links:
1. https://github.com/bigeagle/danmaQ/issues/8#issuecomment-167235412

**Comment by acgtyrant** [comment]
I advise write this license into README.md
